name: "build-test"
on: 
  pull_request:
    branches:
      - main

jobs:
  # make sure build/ci work properly
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build and test
      run: |
        npm install
        npm run all
